on:
  #trigger
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:

  jest_test:

    runs-on: ubuntu-latest

    steps: 
      - uses: actions/checkout@v3

      - name: Run tests

        run: |
          cd frontend
          npm install
          npm test
      
